#!/bin/sh 

# Source debconf library.
. /usr/share/debconf/confmodule

# Get GIT Repo User
db_input critical vedaOffline/gitUser
db_go

# Get GIT Repo Pass
db_input critical vedaOffline/gitPass
db_go
