#!/bin/sh

# Source debconf library.
. /usr/share/debconf/confmodule

# Get GIT User id
db_get vedaOffline/git_user
subtenant_id=$RET

# Get GIT password
db_get vedaOffline/git_pass
uid=$RET

# Display complete message
db_input critical vedaOffline/setup_complete
db_go

# Cleanly exit
db_stop

